/*
-- Query: select * from reserva
LIMIT 0, 1000

-- Date: 2022-06-07 17:02
*/
INSERT INTO `reserva` (`ativo`,`comentarios`,`create_time`,`data_reserva`,`last_update`,`numero_adulto`,`numero_crianca`,`observacoes`,`cliente_id`,`estado_id`,`pagamento_id`,`restaurante_seating_id`,`utilizador_id`) VALUES (1,'bli bli bli bli lbli8',sysdate(),'2022-06-08',sysdate(),2,1,'bla bl bla bla 1',1,1,1,1,1);
INSERT INTO `reserva` (`ativo`,`comentarios`,`create_time`,`data_reserva`,`last_update`,`numero_adulto`,`numero_crianca`,`observacoes`,`cliente_id`,`estado_id`,`pagamento_id`,`restaurante_seating_id`,`utilizador_id`) VALUES (1,'bli bli bli bli lbli8',sysdate(),'2022-06-08',sysdate(),3,1,'bla bl bla bla 1',2,1,2,2,2);
INSERT INTO `reserva` (`ativo`,`comentarios`,`create_time`,`data_reserva`,`last_update`,`numero_adulto`,`numero_crianca`,`observacoes`,`cliente_id`,`estado_id`,`pagamento_id`,`restaurante_seating_id`,`utilizador_id`) VALUES (0,'bli bli bli bli lbli2',sysdate(),'2022-06-07',sysdate(),1,1,'bla bl bla bla 2',2,2,3,1,2);
INSERT INTO `reserva` (`ativo`,`comentarios`,`create_time`,`data_reserva`,`last_update`,`numero_adulto`,`numero_crianca`,`observacoes`,`cliente_id`,`estado_id`,`pagamento_id`,`restaurante_seating_id`,`utilizador_id`) VALUES (0,'bli bli bli bli lbli2',sysdate(),'2022-06-07',sysdate(),4,1,'bla bl bla bla 2',3,2,1,2,1);
INSERT INTO `reserva` (`ativo`,`comentarios`,`create_time`,`data_reserva`,`last_update`,`numero_adulto`,`numero_crianca`,`observacoes`,`cliente_id`,`estado_id`,`pagamento_id`,`restaurante_seating_id`,`utilizador_id`) VALUES (0,'bli bli bli bli lbli2',sysdate(),'2022-06-07',sysdate(),4,1,'bla bl bla bla 2',4,2,1,2,1);
INSERT INTO `reserva` (`ativo`,`comentarios`,`create_time`,`data_reserva`,`last_update`,`numero_adulto`,`numero_crianca`,`observacoes`,`cliente_id`,`estado_id`,`pagamento_id`,`restaurante_seating_id`,`utilizador_id`) VALUES (0,'bli bli bli bli lbli2',sysdate(),'2022-06-07',sysdate(),4,1,'bla bl bla bla 2',5,2,1,2,1);
INSERT INTO `reserva` (`ativo`,`comentarios`,`create_time`,`data_reserva`,`last_update`,`numero_adulto`,`numero_crianca`,`observacoes`,`cliente_id`,`estado_id`,`pagamento_id`,`restaurante_seating_id`,`utilizador_id`) VALUES (0,'bli bli bli bli lbli2',sysdate(),'2022-06-07',sysdate(),4,1,'bla bl bla bla 2',6,2,1,2,1);
INSERT INTO `reserva` (`ativo`,`comentarios`,`create_time`,`data_reserva`,`last_update`,`numero_adulto`,`numero_crianca`,`observacoes`,`cliente_id`,`estado_id`,`pagamento_id`,`restaurante_seating_id`,`utilizador_id`) VALUES (0,'bli bli bli bli lbli2',sysdate(),'2022-06-07',sysdate(),4,1,'bla bl bla bla 2',7,2,1,2,1);
INSERT INTO `reserva` (`ativo`,`comentarios`,`create_time`,`data_reserva`,`last_update`,`numero_adulto`,`numero_crianca`,`observacoes`,`cliente_id`,`estado_id`,`pagamento_id`,`restaurante_seating_id`,`utilizador_id`) VALUES (0,'bli bli bli bli lbli2',sysdate(),'2022-06-07',sysdate(),4,1,'bla bl bla bla 2',8,2,1,2,1);
INSERT INTO `reserva` (`ativo`,`comentarios`,`create_time`,`data_reserva`,`last_update`,`numero_adulto`,`numero_crianca`,`observacoes`,`cliente_id`,`estado_id`,`pagamento_id`,`restaurante_seating_id`,`utilizador_id`) VALUES (0,'bli bli bli bli lbli2',sysdate(),'2022-06-07',sysdate(),4,1,'bla bl bla bla 2',9,2,1,2,1);
INSERT INTO `reserva` (`ativo`,`comentarios`,`create_time`,`data_reserva`,`last_update`,`numero_adulto`,`numero_crianca`,`observacoes`,`cliente_id`,`estado_id`,`pagamento_id`,`restaurante_seating_id`,`utilizador_id`) VALUES (0,'bli bli bli bli lbli2',sysdate(),'2022-06-07',sysdate(),4,1,'bla bl bla bla 2',10,2,1,2,1);
